version: "3"
services:

  sadoparser_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sadoparserai_db
    container_name: sadoparser_bot
    ports:
      - "1283:8000"
    volumes:
      - ./media:/app/media
    environment:
      TZ: Europe/Moscow
    networks:
      - project-network
      
  sadoparserai_db:
    image: postgres:latest
    container_name: sadoparserai_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

networks:
  project-network:

volumes:
  postgres_data:
